swagger: '2.0'
info:
  title: Flash Card API
  version: 1.0.0
  description: Flash Card API implemented with OpenAPI Codegen

tags:
  - name: "Deck"
paths:
  #These are endpoints related to creating the Deck
  /createDeck:
    post:
      summary: Create New Flash Card Deck
      tags:
        - "Deck"
      description: Create New Flash Card Deck
      operationId: createDeck
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: deck
          required: true
          schema:
            $ref: './FlashCardApiComponents.yaml#/components/schemas/Deck'
      responses:
        200:
          description: Deck created successfully
          schema:
            $ref: './FlashCardApiComponents.yaml#/components/schemas/Deck'
        400:
          description: The submitted id is invalid
          schema:
            type: object
            properties:
              error:
                type: string
                example: "The submitted id is invalid"
        404:
          description: The submitted id is not found
          schema:
            type: object
            properties:
              error:
                type: string
                example: "The submitted id is not found"
        500:
          description: Internal Server Error
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Internal Server Error"
  #These are endpoints related to retrieving the Deck
  /retrieveAllDecks:
    get:
      summary: Gets all Flash Card Decks
      tags:
        - "Deck"
      description: Get all Decks of Flash Cards
      operationId: retrieveAllDecks
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: './FlashCardApiComponents.yaml#/components/schemas/Deck'
        500:
          description: Internal Server Error
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Internal Server Error"
  /retrieveDeckById/{id}:
    get:
      summary: Get Flash Card Deck using Deck Id
      tags:
        - "Deck"
      description: Get Flash Card Deck using Deck Id
      operationId: retrieveDeckById
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: Flash Card Deck id
          required: true
          type: integer
      responses:
        200:
          description: Success
          schema:
            $ref: './FlashCardApiComponents.yaml#/components/schemas/Deck'
        400:
          description: The submitted id is invalid
          schema:
            type: object
            properties:
              error:
                type: string
                example: "The submitted id is invalid"
        404:
          description: The submitted id is not found
          schema:
            type: object
            properties:
              error:
                type: string
                example: "The submitted id is not found"
        500:
          description: Internal Server Error
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Internal Server Error"
  /retrieveDeckByName/{name}:
    get:
      summary: Get Flash Card Deck using Deck name
      tags:
        - "Deck"
      description: Get Flash Card Deck using Deck name
      operationId: retrieveDeckByName
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Flash Card Deck name
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: './FlashCardApiComponents.yaml#/components/schemas/Deck'
        400:
          description: The submitted name is invalid
          schema:
            type: object
            properties:
              error:
                type: string
                example: "The submitted name is invalid"
        404:
          description: The submitted name is not found
          schema:
            type: object
            properties:
              error:
                type: string
                example: "The submitted name is not found"
        500:
          description: Internal Server Error
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Internal Server Error"

  #These are endpoints related to updating the Deck
  /updateDeckNameById/{id}:
    patch:
      summary: Update Flash Card Deck Name using Deck Id
      tags:
        - "Deck"
      description: Update Flash Card Deck Name using Deck Id
      operationId: updateDeckNameById
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: integer
          description: "Flash Card Deck id"
          required: true
        - in: query
          name: name
          type: string
          description: "The name that the Flash Card Deck is updated to"
          required: true
      responses:
        200:
          description: Success
          schema:
            type: string
        500:
          description: "Internal Server Error"
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Internal Server Error"
        404:
          description: "The submitted id is not found"
          schema:
            type: object
            properties:
              error:
                type: string
                example: "The submitted id is not found"
        400:
          description: "The submitted id is invalid"
          schema:
            type: object
            properties:
              error:
                type: string
                example: "The submitted id is invalid"
  /addCardIdToDeckById/{id}:
    patch:
      summary: Adds a card ID to a Flash Card Deck using Deck Id
      tags:
        - "Deck"
      description: Adds a card ID to a Flash Card Deck using Deck Id
      operationId: addCardIdToDeckById
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: integer
          description: "Flash Card Deck id"
          required: true
        - in: query
          name: cardId
          type: string
          description: "The card ID that is added to the Flash Card Deck"
          required: true
      responses:
        200:
          description: Success
          schema:
            type: string
        500:
          description: "Internal Server Error"
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Internal Server Error"
        404:
          description: "The submitted id is not found"
          schema:
            type: object
            properties:
              error:
                type: string
                example: "The submitted id is not found"
        400:
          description: "The submitted id is invalid"
          schema:
            type: object
            properties:
              error:
                type: string
                example: "The submitted id is invalid"
  /deleteCardIdToDeckById/{id}:
    patch:
      summary: Remove a card ID from a Flash Card Deck using Deck Id
      tags:
        - "Deck"
      description: Remove a card ID from a Flash Card Deck using Deck Id
      operationId: deleteCardIdFromDeckById
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: integer
          description: "Flash Card Deck id"
          required: true
        - in: query
          name: cardId
          type: string
          description: "The card ID that is added to the Flash Card Deck"
          required: true
      responses:
        200:
          description: Success
          schema:
            type: string
        500:
          description: "Internal Server Error"
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Internal Server Error"
        404:
          description: "The submitted id is not found"
          schema:
            type: object
            properties:
              error:
                type: string
                example: "The submitted id is not found"
        400:
          description: "The submitted id is invalid"
          schema:
            type: object
            properties:
              error:
                type: string
                example: "The submitted id is invalid"

  #These are endpoints related to deleting the Deck
  /deleteDeckById/{id}:
    get:
      summary: Delete the Flash Card Deck using Deck Id
      tags:
        - "Deck"
      description: Delete the Flash Card Deck using Deck Id
      operationId: deleteDeckById
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: "Flash Card Deck id"
          required: true
          type: integer
      responses:
        200:
          description: Success
          schema:
            type: string
        500:
          description: Internal Server Error
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Internal Server Error"
        404:
          description: The submitted id is not found
          schema:
            type: object
            properties:
              error:
                type: string
                example: "The submitted id is not found"
        400:
          description: The submitted id is invalid
          schema:
            type: object
            properties:
              error:
                type: string
                example: "The submitted id is invalid"
  /deleteDeckByName/{name}:
    get:
      summary: Delete Flash Card Deck using Deck name
      tags:
        - "Deck"
      description: Delete Flash Card Deck using Deck name
      operationId: deleteDeckByName
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: "The Flash Card Deck name"
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            type: string
        500:
          description: Internal Server Error
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Internal Server Error"
        404:
          description: The submitted name is not found
          schema:
            type: object
            properties:
              error:
                type: string
                example: "The submitted name is not found"
        400:
          description: The submitted name is invalid
          schema:
            type: object
            properties:
              error:
                type: string
                example: "The submitted name is invalid"